import { useState, useContext, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { HiOutlineArrowLeft, HiOutlineCheckCircle, HiOutlinePrinter } from 'react-icons/hi';
import PageHeader from '../../components/ui/PageHeader';
import StatusBadge from '../../components/ui/StatusBadge';
import Spinner from '../../components/ui/Spinner';
import { useFetch } from '../../hooks/useFetch';
import { formatDate, formatCurrency } from '../../utils/helpers';
import { payrollService } from '../../services/payroll.service';
import { AuthContext } from '../../context/AuthContext';

const PayrollDetailPage = () => {
  const { id } = useParams();
  const { isAdmin } = useContext(AuthContext);
  const { data: pr, loading, refetch } = useFetch(`/payroll/${id}`);
  const [updating, setUpdating] = useState(false);
  const payslipRef = useRef(null);

  const handleMarkPaid = async () => {
    setUpdating(true);
    try {
      await payrollService.updateStatus(id, 'paid');
      await refetch();
    } catch (err) {
      alert(err?.response?.data?.message || 'Failed to update status');
    } finally {
      setUpdating(false);
    }
  };

  const handlePrint = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    const content = payslipRef.current?.innerHTML || '';
    win.document.write(`
      <html><head><title>Payslip - ${pr?.employeeId?.fullName || ''}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; max-width: 700px; margin: auto; }
        h1 { text-align: center; color: #1e3a5f; margin-bottom: 5px; }
        .subtitle { text-align: center; color: #666; font-size: 14px; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
        th { background: #f9fafb; font-weight: 600; color: #374151; }
        .net-row td { font-weight: 700; font-size: 16px; color: #1e3a5f; border-top: 2px solid #1e3a5f; }
        .label { color: #6b7280; }
        .value { font-weight: 500; }
        .text-right { text-align: right; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #9ca3af; }
        .employee-info { margin-bottom: 24px; }
        .employee-info td { border: none; padding: 4px 12px; }
      </style></head><body>
      <h1>PAYSLIP</h1>
      <p class="subtitle">${pr?.employeeId?.fullName || ''} — ${formatDate(pr?.paymentDate)}</p>
      ${content.replace(/<button[\s\S]*?<\/button>/g, '').replace(/<a[\s\S]*?<\/a>/g, '').replace(/<svg[\s\S]*?<\/svg>/g, '')}
      <div class="footer">Generated by Employee Management System</div>
      <script>window.onload = function() { window.print(); window.close(); }</script>
      </body></html>
    `);
    win.document.close();
  };

  if (loading) return <div className="p-12"><Spinner /></div>;
  if (!pr) return <div className="p-12 text-center text-gray-500">Payroll record not found</div>;

  const overtimePay = (pr.overtimeHours || 0) * (pr.overtimeRate || 0);
  const otherTotal = (pr.otherDeductions || []).reduce((s, d) => s + (d.amount || 0), 0);
  const gross = pr.grossPay || (pr.basicSalary + (pr.bonus || 0) + overtimePay);
  const totalDed = pr.totalDeductions || ((pr.deduction || 0) + (pr.tax || 0) + otherTotal);
  const net = pr.netPay || (pr.totalSalary || gross - totalDed);

  return (
    <div>
      <PageHeader
        title="Payroll Details"
        subtitle={`Payment date: ${formatDate(pr.paymentDate)}`}
        actions={
          <div className="flex items-center gap-2">
            <button onClick={handlePrint}
              className="inline-flex items-center gap-2 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors">
              <HiOutlinePrinter className="w-4 h-4" /> Print / PDF
            </button>
            <Link to="/payroll" className="inline-flex items-center gap-2 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors">
              <HiOutlineArrowLeft className="w-4 h-4" /> Back
            </Link>
          </div>
        }
      />

      <div ref={payslipRef}>
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid grid-cols-1 lg:grid-cols-3 gap-6"
        >
          <div className="lg:col-span-1">
            <div className="bg-white rounded-2xl border border-gray-100 p-6 text-center shadow-sm">
              <div className="w-16 h-16 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center mx-auto mb-3 text-white text-xl font-bold">
                {pr.employeeId?.fullName?.split(' ').map(n => n[0]).join('')}
              </div>
              <h3 className="text-lg font-semibold text-gray-900">{pr.employeeId?.fullName}</h3>
              <p className="text-sm text-gray-500">{pr.employeeId?.position}</p>
              <div className="mt-3"><StatusBadge status={pr.status} /></div>

              {pr.paymentMethod && (
                <p className="text-xs text-gray-400 mt-2">
                  {pr.paymentMethod === 'bank' ? `Bank: ${pr.bankName || ''} ${pr.bankAccount || ''}` :
                   pr.paymentMethod === 'cheque' ? 'Cheque' : 'Cash'}
                </p>
              )}

              {isAdmin && pr.status !== 'paid' && (
                <button
                  onClick={handleMarkPaid}
                  disabled={updating}
                  className="mt-4 w-full inline-flex items-center justify-center gap-2 bg-green-600 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-green-700 disabled:opacity-50 transition-colors"
                >
                  <HiOutlineCheckCircle className="w-4 h-4" />
                  {updating ? 'Updating...' : 'Mark as Paid'}
                </button>
              )}
            </div>
          </div>

          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm">
              <h3 className="text-base font-semibold text-gray-900 mb-4">Salary Breakdown</h3>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Basic Salary</span>
                  <span className="font-medium text-gray-900">{formatCurrency(pr.basicSalary)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Bonus</span>
                  <span className="font-medium text-green-600">+{formatCurrency(pr.bonus || 0)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Overtime ({pr.overtimeHours || 0}h × ${pr.overtimeRate || 0}/h)</span>
                  <span className="font-medium text-green-600">+{formatCurrency(overtimePay)}</span>
                </div>
                <div className="border-t border-gray-100 pt-2 flex justify-between">
                  <span className="text-sm font-semibold text-gray-900">Gross Pay</span>
                  <span className="text-sm font-bold text-gray-900">{formatCurrency(gross)}</span>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm">
              <h3 className="text-base font-semibold text-gray-900 mb-4">Deductions</h3>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500">General Deduction</span>
                  <span className="font-medium text-red-600">-{formatCurrency(pr.deduction || 0)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Tax</span>
                  <span className="font-medium text-red-600">-{formatCurrency(pr.tax || 0)}</span>
                </div>
                {(pr.otherDeductions || []).map((d, i) => (
                  <div key={i} className="flex justify-between text-sm">
                    <span className="text-gray-500">{d.label || 'Additional Deduction'}</span>
                    <span className="font-medium text-red-600">-{formatCurrency(d.amount)}</span>
                  </div>
                ))}
                {otherTotal === 0 && (pr.otherDeductions || []).length === 0 && (
                  <p className="text-sm text-gray-400 italic">No additional deductions</p>
                )}
                <div className="border-t border-gray-100 pt-2 flex justify-between">
                  <span className="text-sm font-semibold text-gray-900">Total Deductions</span>
                  <span className="text-sm font-bold text-red-600">-{formatCurrency(totalDed)}</span>
                </div>
              </div>
            </div>

            <div className="bg-primary-50 rounded-2xl border border-primary-100 p-6 shadow-sm">
              <div className="flex justify-between items-center">
                <span className="text-lg font-bold text-gray-900">Net Pay</span>
                <span className="text-2xl font-bold text-primary-600">{formatCurrency(net)}</span>
              </div>
              <p className="text-xs text-gray-500 mt-1">
                Payment method: {pr.paymentMethod === 'bank' ? 'Bank Transfer' : pr.paymentMethod === 'cheque' ? 'Cheque' : 'Cash'}
                {pr.status === 'paid' ? ' (Paid)' : ''}
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default PayrollDetailPage;
